name: Autograding for Python 2.7 using Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:2.7  # Χρησιμοποιούμε το επίσημο Docker image για Python 2.7

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pytest  # Εγκατάσταση του pytest στο container

    - name: Run tests
      run: |
        pytest  # Εκτέλεση των tests
